name: gpax311
channels:
- defaults
- conda-forge
dependencies:
- python=3.11
- pip>=20.3.3
- conda>=4.9.2
- pip:
    - "jax[cuda13]"
    - git+https://github.com/adaptive-intelligent-robotics/QDax.git@main#egg=qdax
    - -r requirements.txt
    - -r requirements-dev.txt
